### ISSUE TITLE
Request authorization to copy texts and pictures to Wikipedia

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/librepcb-website#42] opened 2019-12-09 20:25 UTC
##### SUMMARY
I have updated this page of wikipedia : https://en.wikipedia.org/wiki/Comparison_of_EDA_software

And today I receive this message : 

> The material was copied from another website, and thus was a violation of Wikipedia's copyright policy. GNU alone is not a compatible license. Please don't add copyright material to Wikipedia.

##### SOLUTION

Can you please authorize me to copy the texts and pictures I need from LibrePCB website to update the above Wikipedia page and create another one for LibrePCB itself ?

If ok, I will link this page to show that you have given me this authorization.

**Comment by ubruhin** [comment] 2020-04-13 21:01
Oops I completely forgot this issue, sorry :slightly_frowning_face: 

It might be a silly question, but if we put the website content under the [CC-BY-SA-4.0](https://choosealicense.com/licenses/cc-by-sa-4.0/) license, probably the issue is solved "automatically" (i.e. we don't have to manually grant permissions for Wikipedia), isn't it?

It is common practice to put the website of an OpenSource project under this license? But how should files be handled which were not created by us? For example an image like the FOSDEM logo is (obviously) copied from somewhere else and might be licensed differently...

@dbrgn do you have any experience with that?

**Comment by dbrgn** [comment] 2020-04-13 21:05
@ubruhin we can put the *text* (but not media) of the website under CC-BY-SA. Yes, this is something that I've seen other projects doing.

Mentioning the license in the footer would be sufficient, I think. Something like this:

> All text content on this website is licensed under [CC-BY-SA 4.0](...).

**Comment by ubruhin** [comment] 2020-04-13 21:46
OK sounds good :+1: 

And regarding images, I've found [this thread in the Hugo forum](https://discourse.gohugo.io/t/newby-handling-images-license-notice/22223):

> if you are using page resources, then you can list the license info within the front matter. then, your page template can parse this, list it where you want. you could even modify the figure shortcode to automagically insert it into the figcaption.

**Comment by ubruhin** [comment] 2021-12-27 15:31
With #54, the website content is now licensed as CC-BY-3.0 (see text in the website footer) so it should be fine to use the content for a Wikipedia page.

@doom-fr It would be awesome if you could try again to add LibrePCB to Wikipedia, maybe this time it works :slightly_smiling_face:

Closing this issue since the license should be clarified now.

**Closed by ubruhin** 2021-12-27 15:31 UTC
